[build]
  base = "examples"
  command = "cd .. && npm install && npm run build && cd examples && npm run build"

[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200